### ISSUE TITLE
TODO for initial release

### ISSUE THREAD

**Issue by JelleBouma** [JelleBouma/DHAdmin#2]
DHAdmin
- [x] Write code for the initial setup of DHAdmin (creating the right files and folders, changing server.cfg, changing settings.txt)
- [ ] Write a readme.
- [ ] Write documentation for each (DGAdmin) method.

Map (and mode) rotation
- [x] Create a new map rotation system where rotation is random instead of having the same sequence every time. Removing the need for unreliable DGAdmin delays when trying to keep track of the current game mode.
- [x] Allow multiple maps per line. And allow any number of lines.
- [x] Add option to not repeat the same map+mode.
- [x] Appropriately handle comments and white-space.

Achievements
- [x] Add a way to define achievements that are icons shown with your callsign when you kill someone
- [x] Allow an achievement to have multiple objectives and use the rewards system to track these objectives.
- [x] Have a command that shows you the completed and uncompleted objectives.
- [x] Add the option for a message to be broadcast when someone completes an objective.

Damage
- [ ] Allow modification of damage (fall damage, damage of a specific gun or damage while under some effect). This will deprecate john_woo_momentum.

Mapedit
- [x] Allow spawning of models, fx and collision with mapedit.
- [x] Allow spawning of weapons that can be picked up with mapedit.
- [x] Allow spawning of search and destroy style objectives with mapedit. This will deprecate settings_snd.
- [x] Load a specific mapedit file on server start so explodables etc will work.
- [x] Add spawning of explodable barrels with collision that is removed when they explode. These will deprecate settings_extra_explodables.
- [ ] Make the map edit commands easy to use and autosave map editing to a map edit file.

HUD
- [x] Add a hud timer to search and destroy objectives.
- [ ] Create a new file for hud editing. Move and refactor the DGAdmin code related to the hud here.

Score
- [x] Track custom scores.
- [x] Create settings that decide an initial score and a winning score.

Rewards
- [x] Make a reward system where rewards can be triggered (not necessarily a positive reward). This will allow great flexibility in defining game modes when there are a decent amount of triggers and reward types.
- [x] Add kill and death reward triggers, with optional restrictions of used weapons/classes.
- [x] Add weapon pickup and "search and destroy objective" reward triggers
- [x] Add speed reward.
- [ ] Add jump height reward.
- [x] Add score, weapon, perk, chat, fx rewards and a reward trigger for having the top score. This will deprecate settings_killionaire.
- [ ] Add a reward trigger for reaching a defined score.
- [x] Add a reward trigger for changing class (selecting for the first time counts too), this will allow to do class specific (constant) rewards that can not carry over to other classes.

Weapons
- [x] Add all weapons to WeaponDictionary.
- [ ] Better handle attachments of weapons, camo weapons should have different models.
